location                              = "UK South"
rg_name                               = "Azure-rg"
appplan_name                          = "newdev-appplan"
vnet_name                             = "newdev-vnet"
subnet_name                           = "newdev-subnet"